# Generated by Django 4.2.9 on 2024-02-06 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_at', models.DateTimeField(auto_now_add=True)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('positive_votes', models.PositiveIntegerField(default=0)),
                ('negative_votes', models.PositiveIntegerField(default=0)),
                ('participation_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('positive_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('negative_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('wilson_score', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('visibility_status', models.CharField(choices=[('visible', 'VISIBLE'), ('hidden', 'HIDDEN')], default='visible', max_length=20)),
                ('comment_content', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_at', models.DateTimeField(auto_now_add=True)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('positive_votes', models.PositiveIntegerField(default=0)),
                ('negative_votes', models.PositiveIntegerField(default=0)),
                ('participation_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('positive_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('negative_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('wilson_score', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('visibility_status', models.CharField(choices=[('visible', 'VISIBLE'), ('hidden', 'HIDDEN')], default='visible', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserContentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('hidden_comments', models.ManyToManyField(blank=True, to='discussable_app.comment')),
                ('hidden_discussions', models.ManyToManyField(blank=True, to='discussable_app.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussable_app.discussion'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussable_app.comment'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('vote', models.IntegerField(choices=[(1, 'POSITIVE'), (-1, 'NEGATIVE'), (0, 'NO_VOTE')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
