# Generated by Django 4.2.9 on 2024-02-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussable_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creation_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='creation_at',
            new_name='created_at',
        ),
    ]
