# Generated by Django 4.2.9 on 2024-02-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='discussion',
            name='creator_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
