# Generated by Django 4.2.9 on 2024-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussable_app', '0002_comment_creator_name_discussion_creator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontentpreference',
            name='preference',
            field=models.CharField(choices=[('show', 'SHOW'), ('hide', 'HIDE'), ('none', 'NONE')], default='none', max_length=10),
        ),
    ]
